[package]
name = "tx2-common"
version = "0.1.0"
edition = "2021"
authors = ["Elise Amber Katze <ml1@katze.sh>"]

[features]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.8.0"
modular-bitfield = "0.11.2"
