use crate::def_multi_reg32;

pub const XUSB_PADCTL_BASE:     usize = 0x0352_0000;
pub const XUSB_HOST_BAR0_BASE:  usize = 0x0353_0000;
pub const XUSB_HOST_CFG_BASE:   usize = 0x0353_8000;
pub const XUSB_DEV_BASE:        usize = 0x0355_0000;

def_multi_reg32!(
    DEV_XHCI_SPARAM = 0,
    DEV_XHCI_DOORBELL = 4,
    DEV_XHCI_EVENT_RING_TABLE_SIZE = 8, //
    DEV_XHCI_EVENT_RING_SEG0_BASE_ADDR_LO = 0x10,
    DEV_XHCI_EVENT_RING_SEG0_BASE_ADDR_HI = 0x14,
    DEV_XHCI_EVENT_RING_SEG1_BASE_ADDR_LO = 0x18,
    DEV_XHCI_EVENT_RING_SEG1_BASE_ADDR_HI = 0x1C,
    DEV_XHCI_EVENT_RING_DEQUEUE_POINTER_LO = 0x20,
    DEV_XHCI_EVENT_RING_DEQUEUE_POINTER_HI = 0x24,
    DEV_XHCI_EVENT_RING_ENQUEUE_POINTER_LO = 0x28,
    DEV_XHCI_EVENT_RING_ENQUEUE_POINTER_HI = 0x2C,
    DEV_XHCI_CONTROL = 0x30,
    DEV_XHCI_STATUS = 0x34,
    DEV_XHCI_RT_IMOD = 0x38,
    DEV_XHCI_PORTSC = 0x3C,
    DEV_XHCI_ECP_LO = 0x40,
    DEV_XHCI_ECP_HI = 0x44,
    DEV_XHCI_MFINDEX = 0x48,
    DEV_XHCI_PORTPM = 0x4C,
    DEV_XHCI_ENDPOINT_HALT_DCI = 0x50,
    DEV_XHCI_ENDPOINT_PAUSE = 0x54,
    DEV_XHCI_ENDPOINT_RELOAD = 0x58,
    DEV_XHCI_ENDPOINT_STATE_CHANGE = 0x5C,
    DEV_XHCI_FLOW_CONTROL = 0x60,
    DEV_XHCI_DEV_NOTIF_LO = 0x64,
    DEV_XHCI_DEV_NOTIF_HI = 0x68,
    DEV_XHCI_PORT_HALT = 0x6C,
    DEV_XHCI_PORT_TM = 0x70,
    DEV_XHCI_ENDPOINT_THREAD_ACTIVE = 0x74,
    DEV_XHCI_ENDPOINT_STOPPED = 0x78,
    DEV_XHCI_STREAMID_CONFIG = 0x7C,
    DEV_XHCI_DEV_SOFT_RESET = 0x84
);


pub const EVENT_RING_HALT: u32 = 1 << 8;

pub const STATUS_IP: u32 = 1 << 4;