[alias]
build-dump-memory-bin = "objcopy --release --no-default-features --features dump-memory -- -O binary payload.bin"
build-dump-instruction-addr-bin = "objcopy --release --no-default-features --features dump-instruction-addr -- -O binary payload.bin"
build-usb-bin = "objcopy --release --no-default-features --features uspee -- -O binary payload.bin"
build-dtbhax-bin = "objcopy --release --no-default-features --features dtbhax -- -O binary dtbhax.bin"
test-local = "test --target aarch64-apple-darwin"

[build]
target = "ccplex-meow-meow.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem", "panic_immediate_abort"]
